package:
  name: variantdetective
  version: "1.0.0"

source:
#  git_rev: 1.0.0
  git_url: https://github.com/OLF-Bioinformatics/VariantDetective.git

requirements:
  build:
    - python>=3.6.10
    - pip
  run:
    - python>=3.6.10
    - minimap2=2.24
    - bwa=0.7.17
    - samtools=1.10
    - picard=2.27.3
    - freebayes=1.3.5
    - gatk4=4.2.6.1
    - clair3=0.1.11
    - vcflib=1.0.2
    - tabix=1.11
    - vcftools=0.1.16
    - bcftools=1.10
    - nanovar=1.3.9
    - bedtools=2.30.0
    - nanosv=1.2.4
    - svim=1.4.2
    - cutesv=1.0.13
    - survivor=1.0.7
    - numpy=1.19.2
    - pandas=1.1.5

about:
  home: https://github.com/OLF-Bioinformatics/VariantDetective
  license: MIT
  summary: Identify short variants and structural variants from raw sequencing data or genomic sequences
